apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi-container
          image: gitopsregistryyourinitials9922.azurecr.io/fast-api-microservice:e4d3b1b636a2b105e29339aa5788284ae9ace059
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: LoadBalancer # This tells Azure to give us a public IP!
  ports:
    - port: 80
      targetPort: 8000
  selector:
    app: fastapi
